version: '3'
services:
  app:
    container_name: formation-nodejs-app
    image: node:8.4.0
    user: node
    entrypoint: npm
    command: start
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    container_name: formation-nodejs-mysql
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=openska
      - MYSQL_DATABASE=formation
